### PR TITLE
fix: footer background position

### LINKED ISSUE #92: Adjust Contact Us section background
### Description

image

The background of the contact us section is misplaced.

### Expected Behaviour

The background should be present behind the textual content of the Contact Us section.

### What happened?

A bug happened!

### Version

https://dscvitchennai-nine.vercel.app/#

### What browsers are you seeing the problem on?

_No response_

### Relevant log output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by jessej-samuel**
### 🛠️ Fixes Issue

Closes #92 

### 👨‍💻 Changes proposed

- convert image to backgroundimg

### 🔧 Check List (Check the type of issue it fixes) 

- [x] Bug Fix
- [ ] New Extension
- [ ] Enhancement
- [ ] Documentation

### ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have done `git pull` before adding my new changes
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by FidalMathew** [comment]
@jessej-samuel could make the background image lighter?

**Comment by jessej-samuel** [comment]
@FidalMathew fixed the opacity

**Comment by Arjun31415** [comment]
@jessej-samuel can u just pull the main, because i have removed the `yarn.lock`

**Comment by FidalMathew** [comment]
@Arjun31415 @jessej-samuel LGTM!

**Comment by jessej-samuel** [comment]
> @jessej-samuel the PR looks good, but could you adjust the spacing a bit to fit the entire "Contact" section to the viewport height? Take a look at the readme.md for reference. Let me know if you understood :)

Yup. I've fixed it now :}

**Pull request merged**
