### PR TITLE
Navbar buttons link fix #81

### LINKED ISSUE #81: broken navbar hyperlinks
### Description

- the navbar hyperlinks only lead to the "home page" (not to and fro as i expected) 

https://user-images.githubusercontent.com/94098024/198199578-0bf2c39b-88d6-4656-b0b2-12894fe8e800.mp4

- the logo hyperlink is broken
image

- the arrow heads are not responsive

[visited the website on: Chrome, Tor, Brave]
//sincere apologies if these bugs are already being addressed or wips but i couldnt find them personally.

### Expected Behaviour

- expected the navbars to lead to the resp page
- expected the logo hyperlink to lead to official social media handles or such
- expected the arrow heads to lead to the next page

### What happened?

- navbar pages lead only to homepage [not responsive when interacted with on the home page]
- logo hyperlink leads to a broken page
- arrow heads are not responsive

### Version

[link provided in the repo]
http://dscvitchennai-nine.vercel.app/

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by ChristanWilbert**
### 🛠️ Fixes Issue

fix for #81 

### 👨‍💻 Changes proposed

make navbar links clickable

Home Team and Contact us buttons lead to corresponding sections of the webpage

### 🔧 Check List (Check the type of issue it fixes) 

- [x] Bug Fix
- [ ] New Extension
- [ ] Enhancement
- [ ] Documentation

### ✔️ Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have done `git pull` before adding my new changes
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by FidalMathew** [comment]
@ChristanWilbert there have been many changes before your PR, could you pull those changes and add them to the website?
Like, the icons have been updated, pics of leads, etc. 

The PR seems to work fine, but in some cases like in the Vision section, is it possible to adjust its offset a bit up?

**Comment by FidalMathew** [comment]
@ChristanWilbert could you check your PR? The links are not working for me.

**Comment by Arjun31415** [comment]
@ChristanWilbert I really don't think I can merge this PR because of so many file changed, i think you need to create a new one because this one is polluted

**Comment by ChristanWilbert** [comment]
OK I will do that

**Pull request closed without merging**
