### PR TITLE
Added Event Section 2 and fixed img tag to Next Image

### PR DESCRIPTION
**Pull request by jaydeepdey03**
### 🛠️ Fixes Issue

Fixed ESLint Next Image tag issue

### 👨‍💻 Changes proposed

Added Events Section

### 🔧 Check List (Check the type of issue it fixes) 

- [x] Bug Fix
- [x] New Extension
- [ ] Enhancement
- [ ] Documentation

### ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have done `git pull` before adding my new changes
- [x] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots
image

### CODE REVIEW

**Comment by jaydeepdey03** [comment]
@FidalMathew @Arjun31415 Please check the PR and suggest changes if needed

**Comment by FidalMathew** [comment]
@jaydeepdey03 kindly take a look at this image(not getting displayed) 
image

**Comment by jaydeepdey03** [comment]
Fixed @FidalMathew

**Comment by FidalMathew** [comment]
LGTM 🚀 @jaydeepdey03

**Pull request merged**
