### PR TITLE
API Endpoint for contributor list wrt #35

### PR DESCRIPTION
**Pull request by pythongiant**
### 🛠️ Fixes Issue

wrt. Issue #35 

### 👨‍💻 Changes proposed

List all the Contributors to the website using the Octokit API. 

### 🔧 Check List (Check the type of issue it fixes) 

- [ ] Bug Fix
- [ ] New Extension
- [x] Enhancement
- [ ] Documentation

### ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have done `git pull` before adding my new changes
- [x] The title of my pull request is a short description of the requested changes.

### 📄 Note to reviewers
We'll need to add an environmental variable `API_URL` in Vercel to make it work. [Here's how to do that](https://vercel.com/docs/concepts/projects/environment-variables)
## 📷 Screenshots

image

### CODE REVIEW

**Review by AbhijithGanesh — APPROVED** [review]
LGTM. Just ensure you add API keys to the repository to avoid failure

**Comment by AbhijithGanesh** [comment]
@pythongiant just rename `api_key` to `process.env.api_key`

**Comment by Arjun31415** [comment]
Can you change the file name to contributors, short forms are a bad practise in API

**Comment by Arjun31415** [comment]
How did you get the keys, we need it so that build does not fail

**Review by Arjun31415 — APPROVED** [review]

**Comment by pythongiant** [comment]
> How did you get the keys, we need it so that build does not fail

Have a look at [this](https://octokit.github.io/rest.js/v19#authentication)

**Pull request merged**
