### PR TITLE
Made the hero section responsive to all screens

### LINKED ISSUE #10: feat: make hero section more responsive
Hi! Right now the hero section has lots of breaks `<br />` viz inconsistent while scaling.
image
Can I work on making it more responsive for screens bigger than mobile? [cuz Idk how the design for mobile looks yet 😅]

### PR DESCRIPTION
**Pull request by jessej-samuel**
### 🛠️ Fixes Issue

Closes #10 

### 👨‍💻 Changes proposed

[feat: make navbar sticky](https://github.com/dscvitc/dscvitchennai/commit/e13db385b906af6b816a8ea298797b1e638ee1e2)
  
[import: Open Sans font (font given in mockup)](https://github.com/dscvitc/dscvitchennai/commit/e9be1dcc20c4e51197f541a4288bdc4e3c6423f4)

  
[fix: fixed some build errors](https://github.com/dscvitc/dscvitchennai/commit/6d5677da3cdfdf1175b58f669d389de41dc396da)
  
[fix: navbar blocking page on mobile](https://github.com/dscvitc/dscvitchennai/commit/59e9189db8e3c91f8ab17e47e61877366eced12f)
  
[fix: made hero section responsive + refactor code](https://github.com/dscvitc/dscvitchennai/commit/dbf26d33cf419f7e3e9cfc1db5c97e401ec12982)
[Merge branch 'dscvitc:main' into main](https://github.com/dscvitc/dscvitchennai/commit/e1968d7e62b5dcaa532412775b7feb2c2d3dc600)

### 🔧 Check List (Check the type of issue it fixes) 

- [x] Bug Fix
- [ ] New Extension
- [ ] Enhancement
- [ ] Documentation

### ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have done `git pull` before adding my new changes
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by Arjun31415** [comment]
This is similar to #37 could you please collaborate

**Comment by Arjun31415** [comment]
Further there is a similar PR merged on dev branch #33 . Please work on the dev branch instead of the main

**Comment by jessej-samuel** [comment]
> Further there is a similar PR merged on dev branch #33 . Please work on the dev branch instead of the main

Changes base to "dev"

**Comment by jessej-samuel** [comment]
Cool🚀

**Pull request merged**
