### PR TITLE
Fixes #45: Updated nav bar and enhanced formatting

### LINKED ISSUE #45: bug: hero image overlaps nav in dev branch
image

Currently, working on this. Will pr a fix.

### PR DESCRIPTION
**Pull request by jessej-samuel**
### 🛠️ Fixes Issue

Closes #45 

### 👨‍💻 Changes proposed

[fix: push nav to top-of-screen](https://github.com/dscvitc/dscvitchennai/commit/ec53fa63d9dabe77a2d70ea6bc483f300fbd5b74)
[removed: redundant down arrow](https://github.com/dscvitc/dscvitchennai/commit/12a98c26800f93816d8e5fbf10eff81bf8257447)
[feat: optimize nav links](https://github.com/dscvitc/dscvitchennai/commit/d3839602968aab395bd663debe836410e7615a0a)
[fix: set the width clip to whole content](https://github.com/dscvitc/dscvitchennai/commit/e6cd2a144f85e58fd936c33824b4b534c4618bb8)
[add: comments explaining changes](https://github.com/dscvitc/dscvitchennai/commit/4ccd1ed17a86e76f645418105e93908d6c85e89e)
[add: link to vision section](https://github.com/dscvitc/dscvitchennai/commit/635e6211d924b50330699edf21f1135e7f24f117)
[formatting](https://github.com/dscvitc/dscvitchennai/commit/f06bf862b544714d394bcf2e3a34a970c835595e)
[Merge branch 'dscvitc:main' into main](https://github.com/dscvitc/dscvitchennai/commit/808a705d22f174b1951128dd519b6132fc5be0c6)

### 🔧 Check List (Check the type of issue it fixes) 

- [x] Bug Fix
- [ ] New Extension
- [x] Enhancement
- [ ] Documentation

### ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have done `git pull` before adding my new changes
- [x] The title of my pull request is a short description of the requested changes.

### 📄 Note to reviewers
I pulled from the 'main' branch of the base repo and pulled a bunch of readme commits by mistake :|
## 📷 Screenshots
image

### CODE REVIEW

**Comment by Arjun31415** [comment]
ok why are there so many commits please use the dev branch then checkout your branch. It is polluting the repo with so many merge requests and other commits not related to this PR

**Comment by jessej-samuel** [comment]
> ok why are there so many commits please use the dev branch then checkout your branch. It is polluting the repo with so many merge requests and other commits not related to this PR

Yeeet! Pulled from main by mistake 😬

**Comment by jessej-samuel** [comment]
@Arjun31415 Anyway, all these are just commits that were made directly into main after dev was created. So, it won't change any commit. I'll have to fork the repo with the "dev" branch, only after deleting my existing fork (deleting all my current commits). Once this gets merged, I'll fork it with the dev branch 🥲

**Comment by jessej-samuel** [comment]
Thanks @Arjun31415 👍

**Pull request merged**
