### PR TITLE
Update board member card look and feel

### LINKED ISSUE #102: [FEATURE] Improve Board Member cards
### Description

Currently the board member card only contains profile picture, name and role. But as per the data structure in [BoardMember.js](https://github.com/dscvitc/dscvitchennai/blob/main/data/BoardMember.js) there are three fields that are not currently in use 

```
description
LinkedIn Link
Github Link
```

I propose we make use of those fields and add them to the BoardMember Card for a more personalized feel

### Expected Behaviour

_No response_

### Current Behaviour

This is how it looks currently <br />
old board member

## Proposed Behavior

I propose we make it into this format instead that makes use of all the data fields <br />

board member

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Aditya-Jyoti**
### 👨‍💻 Changes proposed

Proposed an update in the look of Board Member cards and made use of previously unused parameters

### 🔧 Check List (Check the type of issue it fixes)

- [ ] Bug Fix
- [ ] New Extension
- [x] Enhancement
- [ ] Documentation

### ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have done `git pull` before adding my new changes
- [x] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots

Screenshot 2023-10-02 210811

### CODE REVIEW

**Comment by Aditya-Jyoti** [comment]
@EmmanuelAllanMJ @vaibhavTekk could you review this PR

**Comment by EmmanuelAllanMJ** [comment]
Can you update the names and their designation, use dummy data if not provided

**Comment by vaibhavTekk** [comment]
@Aditya-Jyoti just to clarify, this just updates the components and not the data correct ?

**Comment by Aditya-Jyoti** [comment]
Will push with dummy data once I'm back from class in another PR. This one was just for the CSS updates

**Comment by Aditya-Jyoti** [comment]
> @Aditya-Jyoti just to clarify, this just updates the components and not the data correct ?

Yes, just updates the components

**Comment by vaibhavTekk** [comment]
@Aditya-Jyoti There's some overlap between the image and the text, can you make it so that all the images show up with the same width and height ?

image

**Comment by Aditya-Jyoti** [comment]
> @Aditya-Jyoti There's some overlap between the image and the text, can you make it so that all the images show up with the same width and height ?
> 
> image
> 

I faced the same issue when working with the date. The easiest method to solve it is to crop all images inside the `public/leads/` folder to a square format.

I chose the manual method because for some reason setting the witdh and height as well as the padding gave inconsistent results.

I'll make cropping changes once I'm back from class

**Comment by Aditya-Jyoti** [comment]
closing this PR, will open a new one with all the fixes.

**Pull request closed without merging**
