### PR TITLE
Closes #60: Fix Nav 🍔 on mobile

### LINKED ISSUE #60: bug: hamburger in navbar on mobile doesn't show
The button here https://github.com/dscvitc/dscvitchennai/blob/e81e7eed5e174d39216c2ddb1ca23d9e25b0bb37/components/Navbar.js#L21 is not visible, as color is `white` inside svg.

Also, https://github.com/dscvitc/dscvitchennai/blob/e81e7eed5e174d39216c2ddb1ca23d9e25b0bb37/components/Navbar.js#L61 this line doesn't run due to normal quotations in place of backticks. This makes the whole navbar persist on mobile screens too.

Currently the screen looks like this:
image

It should look like:
image

### PR DESCRIPTION
**Pull request by jessej-samuel**
### 🛠️ Fixes Issue

Closes #60 

### 👨‍💻 Changes proposed

- [x] [fix: made 🍔 icon visible](https://github.com/dscvitc/dscvitchennai/commit/43d8f752e76118be45e49f35692b67fee8c8f2ca)
- [x] [remove: reused code](https://github.com/dscvitc/dscvitchennai/commit/296c3887d683233e9d695e6dde53586ddb429f28)

### 🔧 Check List (Check the type of issue it fixes) 

- [x] Bug Fix
- [ ] New Extension
- [x] Enhancement
- [ ] Documentation

### ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have done `git pull` before adding my new changes
- [x] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots
image

### CODE REVIEW

**Comment by FidalMathew** [comment]
@jessej-samuel Kindly take note of this issue. 
image

**Comment by jessej-samuel** [comment]
Hey @FidalMathew , I noticed this. It's being caused by the `vision` section. Not related to #60. Probably open a separate issue would be clean. Or else I can fix the vision section too here itself. What do you say 🤔

image

**Comment by Arjun31415** [comment]
Why do you believe it is because of the vision section, isn't the vision section width correct

**Comment by jessej-samuel** [comment]
Check the chrome inspector. The vision sections width exceeds the html's root width

**Comment by FidalMathew** [comment]
Padding seems to fix the issue. @jessej-samuel @Arjun31415 
Remove the margins.
image

**Comment by jessej-samuel** [comment]
Cool! I thought the gaps were causing it lol. I'll add that in a commit shortly

**Comment by jessej-samuel** [comment]
Alright, that's fixed ;) I really like how the site has turned out 😸

**Comment by Arjun31415** [comment]
@FidalMathew add the hacktoberfest accepted tag

**Pull request merged**
