### PR TITLE
img tag replaced with Image

### PR DESCRIPTION
**Pull request by sn10-debug**
#20 

- [x] Bug Fix
- [x] New Extension
- [✔️ ] Enhancement
- [x] Documentation

- [ ✔️ ] My code follows the code style of this project.
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules
- [ ✔️] I have done `git pull` before adding my new changes
- [ ✔️] The title of my pull request is a short description of the requested changes.

### 📄 Note to reviewers
The code was successfully build and complied at the local system with the changes

### CODE REVIEW

**Comment by sn10-debug** [comment]
We can install sharp for better image processing as well. If needed i can add it @Arjun31415 . Please do respond should i include it or not

**Comment by Arjun31415** [comment]
> We can install sharp for better image processing as well. If needed i can add it @Arjun31415 . Please do respond should i include it or not 

There is no need for that .
I will merge it soon

**Comment by sn10-debug** [comment]
@Arjun31415 Ohk Thank you so much! 😊

**Comment by sn10-debug** [comment]
@Arjun31415  Can you please assign me this issue?

**Comment by Arjun31415** [comment]
> @Arjun31415  Can you please assign me this issue?

I cannot do that because it has been assigned to someone else. Could you work  on some other issue ?

**Comment by sn10-debug** [comment]
@Arjun31415 Can i expect some more issues in the repo?

**Pull request closed without merging**
