### PR TITLE
Carousel containing the heads of the GDSC has been added.

### PR DESCRIPTION
**Pull request by sn10-debug**
A Carousel has been made using bootstrap and added to the homepage of the GDSC website.

- [ ] Bug Fix
- [ ✔️] New Extension
- [ ✔️] Enhancement
- [ ] Documentation

- [ ✔️] My code follows the code style of this project.
- [ ✔️] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ✔️] My changes generate no new warnings
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ✔️] I have done `git pull` before adding my new changes
- [ ✔️] The title of my pull request is a short description of the requested changes.

### 📄 Note to reviewers

I have added the Carousel to the Homepage of the GDSC website.

### CODE REVIEW

**Comment by FidalMathew** [comment]
We are having Tailwind as our CSS framework and using Bootstrap along with that isn't preferred. 
@Arjun31415 what do you say?

**Comment by FidalMathew** [comment]
@sn10-debug I wanted to add the point that, you should let us know what your gonna build and how. So, that we can warn you of the possible errors you will face while developing the application.

**Comment by Arjun31415** [comment]
> 

yeah we have tailwind, so we wont be accepting bootstrap
Please use react-material-ui if you need it

**Comment by sn10-debug** [comment]
Ohkk i will use react material ui to get the component

**Comment by sn10-debug** [comment]
> @sn10-debug I wanted to add the point that, you should let us know what your gonna build and how. So, that we can warn you of the possible errors you will face while developing the application.

I won't repeat the mistake again.

**Comment by sn10-debug** [comment]
@Arjun31415 can I ask my queries in the WhatsApp before building something?

**Pull request closed without merging**
